
    create table ACCOUNT (
        id bigint generated by default as identity,
        account_email varchar(255),
        account_firstname varchar(255) not null,
        account_inscriptionDate timestamp,
        account_activated boolean not null,
        account_premium boolean not null,
        account_lastConnectionDate timestamp,
        account_lastname varchar(255) not null,
        account_password varchar(255) not null,
        account_expirationDate timestamp,
        account_role varchar(255),
        account_screenname varchar(255) not null,
        primary key (id)
    );

    create table ACCOUNT_PARTY (
        members_id bigint not null,
        teams_id bigint not null,
        primary key (members_id, teams_id)
    );

    create table CODE (
        id bigint generated by default as identity,
        agent_id bigint,
        party_id bigint,
        primary key (id)
    );

    create table PARTY (
        id bigint generated by default as identity,
        party_creationDate timestamp,
        party_elo integer,
        party_language integer,
        party_name varchar(255),
        creator_id bigint,
        primary key (id)
    );

    create table WEB_AGENT (
        id bigint generated by default as identity,
        isActivated boolean,
        isPremium boolean,
        WarType integer,
        primary key (id)
    );

    alter table ACCOUNT 
        add constraint UK_jkd9cix86ciqqcm6do9odr3h7  unique (account_email);

    alter table ACCOUNT 
        add constraint UK_f4lc6mbyr2oahgta5npnx74l  unique (account_screenname);

    alter table PARTY 
        add constraint UK_6f9crrkedyvu40ib31ca4s3w3  unique (party_name);

    alter table ACCOUNT_PARTY 
        add constraint FK_thjxm36muk6f3mwrvppsv00r4 
        foreign key (teams_id) 
        references PARTY;

    alter table ACCOUNT_PARTY 
        add constraint FK_8yp9nyvbnahs7errjtnixjfyn 
        foreign key (members_id) 
        references ACCOUNT;

    alter table CODE 
        add constraint FK_mav01bmkm1harefpd70s7bq9t 
        foreign key (agent_id) 
        references WEB_AGENT;

    alter table CODE 
        add constraint FK_sqfwawkmgtqmb67r2my477avv 
        foreign key (party_id) 
        references PARTY;

    alter table PARTY 
        add constraint FK_k1774sand3ceowkyfblvuhp2v 
        foreign key (creator_id) 
        references ACCOUNT;
